language: php
services:
  - mysql

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.2'
      env: STATIC_ANALYSIS=true

    - os: linux
      php: '7.2'

cache:
  directories:
    - $HOME/.composer/cache
before_script:
  # disable xdebug if not coverage
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - mysql -u root --password="" < database.sql

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --ignore-platform-reqs

script:
  # static analysis
  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
      composer check-cs
      composer phpstan
    fi
  # tests
  - composer phpunit

after_script:
  - |
    if [[ $COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
      vendor/bin/phpunit --coverage-clover coverage.xml
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      php php-coveralls.phar --verbose
    fi